// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyKeyVault.Web.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyKeyVault.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251221065328_AddWechatScrapeLog")]
    partial class AddWechatScrapeLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.AIConfig", b =>
                {
                    b.Property<long>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ConfigId"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConfigId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AIConfigs");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.AccountTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("AccountId", "TagId")
                        .IsUnique();

                    b.ToTable("AccountTags");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.BalanceSheet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AccExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AccReceivable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AccountsPay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AccountsReceiv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AccountsReceivBill")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AcctPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ActingTradingSec")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ActingUwSec")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AdvReceipts")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AgencyBusLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AmorExp")
                        .HasColumnType("numeric");

                    b.Property<string>("AnnDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("BondPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CapRese")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CashReserCb")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CbBorr")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Cip")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CipTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ClientDepos")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ClientProv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CommPayable")
                        .HasColumnType("numeric");

                    b.Property<string>("CompType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("ConstMaterials")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ContractAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ContractLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CostFinAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DebtInvest")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DecrInDisbur")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DeferIncNonCurLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DeferTaxAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DeferTaxLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DeferredInc")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Depos")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DeposIbDeposits")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DeposInOthBfi")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DeposOthBfi")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DeposReceived")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DerivAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DerivLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DivPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DivReceiv")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("EndType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("EstimatedLiab")
                        .HasColumnType("numeric");

                    b.Property<string>("FAnnDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("FaAvailForSale")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FairValueFinAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FixAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FixAssetsTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FixedAssetsDisp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ForexDiffer")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Goodwill")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("HfsAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("HfsSales")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("HtmInvest")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IndemPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IndepAcctAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IndeptAccLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IntPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IntReceiv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IntanAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Inventories")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InvestAsReceiv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InvestLossUnconf")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InvestRealEstate")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LeaseLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LendingFunds")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LoanOthBank")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LoantoOthBankFi")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LongPayTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LtAmorExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LtBorr")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LtEqtInvest")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LtPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LtPayrollPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LtRec")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinorityInt")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MoneyCap")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NcaWithin1y")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NonCurLiabDue1y")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NotesPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NotesReceiv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OilAndGasAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OrdinRiskReser")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthCompIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthCurAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthCurLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthDebtInvest")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthEqInvest")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthEqPpbond")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthEqtTools")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthEqtToolsPShr")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthIlliqFinAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthNca")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthNcl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthPayTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthRcvTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthReceiv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PayableToReinsurer")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Payables")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PayrollPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PhInvest")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PhPledgeLoans")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PledgeBorr")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PolicyDivPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrecMetals")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PremReceivAdva")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PremiumReceiv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Prepayment")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ProducBioAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PurResaleFa")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RAndD")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ReceivFinancing")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RefundCapDepos")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RefundDepos")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ReinsurReceiv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ReinsurResReceiv")
                        .HasColumnType("numeric");

                    b.Property<string>("ReportType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("ReserLinsLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ReserLthinsLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ReserOutstdClaims")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ReserUnePrem")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RrReinsLinsLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RrReinsLthinsLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RrReinsOutstdCla")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RrReinsUnePrem")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RsrvInsurCont")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SettRsrv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SoldForRepurFa")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpecialRese")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpecificPayables")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("StBondsPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("StBorr")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("StFinPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SurplusRese")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TaxesPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TimeDeposits")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalCurAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalCurLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalHldrEqyExcMinInt")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalHldrEqyIncMinInt")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalLiabHldrEqy")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalNca")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalNcl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalShare")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TradAsset")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TradingFl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TransacSeatFee")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TreasuryShare")
                        .HasColumnType("numeric");

                    b.Property<string>("TsCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("UndistrPorfit")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdateFlag")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("UseRightAssets")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("TsCode");

                    b.HasIndex("TsCode", "EndDate")
                        .IsUnique();

                    b.ToTable("BalanceSheets");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.CallLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ParamsHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiName");

                    b.HasIndex("AppId", "RequestAt");

                    b.ToTable("CallLogs");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.CashflowStatement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AmortIntangAssets")
                        .HasColumnType("numeric");

                    b.Property<string>("AnnDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("BegBalCash")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BegBalCashEqu")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CCashEquBegPeriod")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CCashEquEndPeriod")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CDispWithdrwlInvest")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CFrOthOperateA")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CFrSaleSg")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CInfFrOperateA")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CPaidForTaxes")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CPaidGoodsS")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CPaidInvest")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CPaidToForEmpl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CPayAcqConstFilta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CPayClaimsOrigInco")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CPayDistDpcpIntExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CPrepayAmtBorr")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CRecpBorrow")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CRecpCapContrib")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CRecpReturnInvest")
                        .HasColumnType("numeric");

                    b.Property<string>("CompType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("ConvCopbondsDueWithin1y")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ConvDebtIntoCap")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CreditImpaLoss")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DecrDefIncTaxAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DecrDeferredExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DecrInventories")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DecrOperPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DeprFaCogaDpba")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EffFxFluCash")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EndBalCash")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EndBalCashEqu")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("EndType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FAnnDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("FaFncLeases")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FinanExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FreeCashflow")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IfcCashIncr")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ImNIncrCashEqu")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ImNetCashflowOperAct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InclCashRecSaims")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InclDvdProfitPaidScMs")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IncrAccExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IncrDefIncTaxLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IncrOperPayable")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InvestLoss")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LossDispFilta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LossFvChg")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LossScrFa")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LtAmortDeferredExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NCapIncrRepur")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NCashFlowsFncAct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NCashflowAct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NCashflowInvAct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NDeposIncrFi")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NDispSubsOthBiz")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NIncBorrOthFi")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NIncrCashCashEqu")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NIncrCltLoanAdv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NIncrDepCbob")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NIncrDispFaas")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NIncrDispTfa")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NIncrInsuredDep")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NIncrLoansCb")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NIncrLoansOthBank")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NIncrPledgeLoan")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NRecpDispFilta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NRecpDispSobu")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NReinsurPrem")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NetCashReceSec")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NetDismCapitalAdd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NetProfit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthCashPayOperAct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthCashRecpRalFncAct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthCashpayRalFncAct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthLossAsset")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthPayRalInvAct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthRecpRalInvAct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Others")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PayCommInsurPlcy")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PayHandlingChrg")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PremFrOrigContr")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ProcIssueBonds")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ProvDeprAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RecpTaxRends")
                        .HasColumnType("numeric");

                    b.Property<string>("ReportType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("StCashOutAct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("StotCashInFncAct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("StotCashoutFncAct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("StotInflowsInvAct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("StotOutInvAct")
                        .HasColumnType("numeric");

                    b.Property<string>("TsCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("UnconInvestLoss")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdateFlag")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("UseRightAssetDep")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("TsCode");

                    b.HasIndex("TsCode", "EndDate")
                        .IsUnique();

                    b.ToTable("CashflowStatements");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.IncomeStatement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AdjLossgain")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AdminExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AmodcostFinAssets")
                        .HasColumnType("numeric");

                    b.Property<string>("AnnDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("AssInvestIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AssetDispIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AssetsImpairLoss")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BasicEps")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BizTaxSurchg")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CapitComstockDiv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CommExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CommIncome")
                        .HasColumnType("numeric");

                    b.Property<string>("CompType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("CompensPayout")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CompensPayoutRefu")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ComprIncAttrMS")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ComprIncAttrP")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ComsharePayableDvd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ContinuedNetProfit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CreditImpaLoss")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DilutedEps")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DistableProfit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DistrProfitShrhder")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DivPayt")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ebit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ebitda")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("EndNetProfit")
                        .HasColumnType("numeric");

                    b.Property<string>("EndType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FAnnDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("FinExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FinExpIntExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FinExpIntInc")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ForexGain")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FvValueChgGain")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IncomeTax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InsurReserRefu")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InsuranceExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IntExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IntIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InvestIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinorityGain")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NAssetMgIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NCommisIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NIncomeAttrP")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NOthBIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NOthIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NSecTbIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NSecUwIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NcaDisploss")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NetAfterNrLpCorrect")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NetExpoHedgingBenefits")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NonOperExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NonOperIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OperCost")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OperExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OperateProfit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthBIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthComprIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthImpairLossAssets")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OthIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OtherBusCost")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OutPrem")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PremEarned")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PremIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PremRefund")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrfsharePayableDvd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RdExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ReinsCostRefund")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ReinsExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ReinsIncome")
                        .HasColumnType("numeric");

                    b.Property<string>("ReportType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("ReserInsurLiab")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SellExp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TComprIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalCogs")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalOpcost")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalProfit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalRevenue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TransferHousingImprest")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TransferOth")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TransferSurplusRese")
                        .HasColumnType("numeric");

                    b.Property<string>("TsCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("UndistProfit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("UnePremReser")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdateFlag")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WithdraBizDevfund")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WithdraLegalPubfund")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WithdraLegalSurplus")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WithdraOthErsu")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WithdraReseFund")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WorkersWelfare")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("TsCode");

                    b.HasIndex("TsCode", "EndDate")
                        .IsUnique();

                    b.ToTable("IncomeStatements");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.StockBasic", b =>
                {
                    b.Property<string>("TsCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Area")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CurrType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateOnly?>("DelistDate")
                        .HasColumnType("date");

                    b.Property<string>("EnName")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Exchange")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Fullname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Industry")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("IsHs")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<DateOnly?>("ListDate")
                        .HasColumnType("date");

                    b.Property<string>("Market")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TsCode");

                    b.ToTable("StockBasics");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.StockDaily", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Change")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Close")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("High")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Open")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PctChg")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PreClose")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date");

                    b.Property<string>("TsCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Vol")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("TradeDate");

                    b.HasIndex("TsCode");

                    b.HasIndex("TsCode", "TradeDate")
                        .IsUnique();

                    b.ToTable("StockDailies");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.Tag", b =>
                {
                    b.Property<long>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TagId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagId");

                    b.HasIndex("UserId", "TagName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.TermsAcceptance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Version")
                        .IsUnique();

                    b.ToTable("TermsAcceptances");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.TushareApp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("CallCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EncryptedSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("TushareApps");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.UserKeys", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CryptoVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KdfParams")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KdfSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WrappedDEK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserKeys");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.VaultAccount", b =>
                {
                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AccountId"));

                    b.Property<string>("AccountNameEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoteEncrypted")
                        .HasColumnType("text");

                    b.Property<string>("PasswordEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccountId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.WechatArticle", b =>
                {
                    b.Property<long>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ArticleId"));

                    b.Property<string>("ArticleUniqueId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("HtmlFilePath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ImagesCount")
                        .HasColumnType("integer");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PublishTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaskId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VideosCount")
                        .HasColumnType("integer");

                    b.HasKey("ArticleId");

                    b.HasIndex("ArticleUniqueId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("WechatArticles");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.WechatArticleExtraction", b =>
                {
                    b.Property<long>("ExtractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ExtractionId"));

                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExtractionId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("WechatArticleExtractions");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.WechatScrapeLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("WechatScrapeLogs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MyKeyVault.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MyKeyVault.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyKeyVault.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MyKeyVault.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.AccountTag", b =>
                {
                    b.HasOne("MyKeyVault.Web.Models.VaultAccount", "Account")
                        .WithMany("AccountTags")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyKeyVault.Web.Models.Tag", "Tag")
                        .WithMany("AccountTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.TermsAcceptance", b =>
                {
                    b.HasOne("MyKeyVault.Web.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.WechatArticle", b =>
                {
                    b.HasOne("MyKeyVault.Web.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.WechatArticleExtraction", b =>
                {
                    b.HasOne("MyKeyVault.Web.Models.WechatArticle", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.Tag", b =>
                {
                    b.Navigation("AccountTags");
                });

            modelBuilder.Entity("MyKeyVault.Web.Models.VaultAccount", b =>
                {
                    b.Navigation("AccountTags");
                });
#pragma warning restore 612, 618
        }
    }
}
