CREATE TABLE IF NOT EXISTS sfrost_blog_posts (
  id uuid PRIMARY KEY,
  title varchar(160) NOT NULL,
  summary varchar(320) NOT NULL DEFAULT '',
  content text NOT NULL,
  status varchar(16) NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'published')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz NULL
);

CREATE TABLE IF NOT EXISTS sfrost_blog_tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(40) NOT NULL,
  normalized_name varchar(80) NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sfrost_blog_post_tags (
  post_id uuid NOT NULL REFERENCES sfrost_blog_posts(id) ON DELETE CASCADE,
  tag_id bigint NOT NULL REFERENCES sfrost_blog_tags(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, tag_id)
);

CREATE INDEX IF NOT EXISTS ix_sfrost_blog_posts_public
  ON sfrost_blog_posts (published_at DESC)
  WHERE status = 'published';

CREATE INDEX IF NOT EXISTS ix_sfrost_blog_post_tags_tag
  ON sfrost_blog_post_tags (tag_id, post_id);
